query Articles ($status: String!, $locale: String!, $featured: Boolean!, $limit: Int = -1) {
	Articles (filter: {status: {_eq: $status}, featured: {_eq: $featured}}, limit: $limit) {
		translations(filter: {languages_code: {code: {_eq: $locale}}}) {
			title
			slug
			description @skip(if: $featured)
			body @skip(if: $featured)
		}
		date_created
		date_updated
		tags {
			Tag_id {
				title
			}
		}
		illustration {
			id
            title
		}
	}
}