query Articles {
    articles {
        data {
            attributes {
                title,
                body,
                illustration {
                    data {
                        attributes {
                            url
                        }
                    }
                }
                tags {
                    data {
                        attributes {
                            title
                        }
                    }
                }
            }
        }
    }
}
