query Article($slug: String!) {
	Articles_translations(filter: {slug: {_eq: $slug}}) {
		title
		slug
		body
		description
		Articles_id {
			date_created
			date_updated
			tags {
				Tag_id {
					title
				}
			}
			illustration {
				id
				title
			}
		}
	}
}