query Articles($filters: Articles_filter, $locale: String!, $featured: Boolean! $limit: Int = -1) {
	Articles_translations(limit: $limit, filter: {languages_code: {code: {_eq: $locale}}, Articles_id: $filters}) {
		title
		slug
		body @skip(if: $featured)
        description @skip(if: $featured)
		Articles_id {
			date_created @skip(if: $featured)
			date_updated @skip(if: $featured)
			tags {
				Tag_id {
					title
				}
			}
			illustration {
				id
				title
			}
		}
	}
}