mutation SendComment($name: String!, $email: String!, $content: String!, $article_id: Int!, $comment_id: Int) {
	create_Comments_item(
		data: {
			name: "Coucou les choupinous"
			email: "jlevarato@pm.me"
			content: "Super article omfg"
			article_id: 2
		}
	) {
		id
	}
}