query ByTag ($tag: String!) {
    Articles (filter: {tags: {Tag_id: {title: {_eq:  $tag}}}}) {
        title
        slug
        illustration {
			id
			title
		}
    }

    Project (filter: {tags: {Tag_id: {title: {_eq:  $tag}}}}) {
        title
        slug
        illustration {
			id
			title
		}
    }
}