query FeaturedArticles {
    articles(filters: {featured: {eq: true}}, pagination: {limit: 6}) {
        data {
            attributes {
                title,
                featured,
                body,
                illustration {
                    data {
                        attributes {
                            url
                        }
                    }
                }
                tags {
                    data {
                        attributes {
                            title
                        }
                    }
                }
            }
        }
    }
}
