query FeaturedArticles {
    Articles(
        filter: {
            featured: {_eq: true},
            status: {_eq: "published"}
        },
        limit: 3
    ) {
        title
        slug
        tags {
            Tag_id {
                title
            }
        }
        illustration {
            id
            title
        }
    }
}
