query Homepage {
    Homepage {
        fullname
        baseline
        user {
            title
            id
        }
        icon {
            title
            id
        }
        description
        links
    }
}
