query Homepage {
	Homepage {
		fullname
		baseline
		description
		links
		translations {
			languages_code {
				code
			}
			baseline
			description
		}
		icon {
			id
			title
		}
		user {
			id
			title
		}
	}
}