query Homepage ($showInfos: Boolean = true) {
    Homepage {
        fullname
        baseline
        links

        icon {
            title
            id
        }

        user @include(if: $showInfos) {
            title
            id
        }

        description @include(if: $showInfos)
    }
}
