query Projects($filters: Project_translations_filter) {
	Project_translations(filter: $filters) {
		title
		slug
		body
		description
		Project_id {
			date_created
			date_updated
			repo_link
			website
			tags {
				Tag_id {
					title
				}
			}
			illustration {
				id
				title
			}
		}
	}
}