query Project {
    Project(filter: {status: {_eq: "published"}}) {
        title
        website
        repo_link
        slug
        body
        illustration {
            filename_download
        }
        date_created
        date_updated

        tags {
            Tag_id {
                title
            }
        }
    }
}
