query Projects ($filter: Project_filter, $limit: Int = -1) {
    Project(
            filter: $filter,
            limit: $limit
		) {
		title
		slug
		tags {
			Tag_id {
				title
			}
		}
		illustration {
			id
			title
		}
    }
}
