query Project ($search: String!) {
    Project(
        search: $search,
        filter: {status: {_eq: "published"}}
    ) {
        title
        website
        repo_link
        slug
        description
        body
        illustration {
			id
			title
		}
        date_created
        date_updated

        tags {
            Tag_id {
                title
            }
        }
    }
}
